"""Executable mirror of the preregistered AdaptiveRL shift protocol.

This package contains the frozen constants, seed schedule, recovery-endpoint,
and statistical-analysis primitives defined normatively in
``docs/research/adaptive_rl_hypothesis.md`` (Issue #98 / PR #168).

Scope: these helpers make the protocol mechanically checkable. They do **not**
implement the future Adaptive treatment harness, do not modify
``shift_runner.py``, and do not make any experimental cell executable.
"""

from adaptive_rl.protocol.adaptation import (
    AdaptationAdapter,
    PostShiftEpisode,
    Transition,
    UpdateBatch,
    build_update_batch,
    call_update_atomically,
    validate_block_sequence,
)
from adaptive_rl.protocol.constants import (
    ALPHA,
    BOOTSTRAP_REPS,
    BOOTSTRAP_SEED,
    CONFIG_TEST_POOL,
    CONFIG_TRAIN_POOL,
    HORIZON,
    K_PRE,
    MIN_DEGRADATION_SE_MULTIPLIER,
    MIN_VALID_N,
    N_POST,
    N_UPDATE,
    PERSISTENCE,
    PINNED_COMMIT,
    PLANNED_N,
    PRIMARY_CELLS,
    PROTOCOL_VERSION,
    RECOVERY_THRESHOLD,
    SEED_VALUE_MAX,
    TRAINING_SEEDS,
    WINDOW,
)
from adaptive_rl.protocol.recovery import (
    NON_RECOVERY_STATUSES,
    RECOVERY_STATUSES,
    STATUS_DEGRADATION_BELOW_RESOLUTION,
    STATUS_NO_DEGRADATION,
    STATUS_RECOVERED,
    STATUS_RIGHT_CENSORED,
    RecoveryResult,
    compute_recovery,
    final_window_return,
    final_window_success_rate,
    recovery_threshold_met,
    trailing_window_means,
)
from adaptive_rl.protocol.seeds import (
    PHASES,
    build_schedule,
    derive_seed,
    frozen_schedule,
    schedule_fingerprint,
    validate_schedule,
)
from adaptive_rl.protocol.statistics import (
    IMPUTATION_DIRECTIONS,
    FamilyDecision,
    PairedTTest,
    SignTestResult,
    WilcoxonResult,
    bootstrap_percentile_ci,
    cohen_dz,
    decide_family,
    exact_sign_test,
    exact_wilcoxon_signed_rank,
    holm_adjust,
    impute_differences,
    paired_differences,
    paired_t_interval,
    paired_t_test,
    student_t_cdf,
    student_t_ppf,
)

__all__ = [
    "AdaptationAdapter",
    "ALPHA",
    "BOOTSTRAP_REPS",
    "BOOTSTRAP_SEED",
    "CONFIG_TEST_POOL",
    "CONFIG_TRAIN_POOL",
    "FamilyDecision",
    "HORIZON",
    "IMPUTATION_DIRECTIONS",
    "K_PRE",
    "MIN_DEGRADATION_SE_MULTIPLIER",
    "MIN_VALID_N",
    "NON_RECOVERY_STATUSES",
    "N_POST",
    "N_UPDATE",
    "PHASES",
    "PINNED_COMMIT",
    "PLANNED_N",
    "PRIMARY_CELLS",
    "PROTOCOL_VERSION",
    "PairedTTest",
    "PERSISTENCE",
    "PostShiftEpisode",
    "RECOVERY_STATUSES",
    "RECOVERY_THRESHOLD",
    "RecoveryResult",
    "SEED_VALUE_MAX",
    "STATUS_DEGRADATION_BELOW_RESOLUTION",
    "STATUS_NO_DEGRADATION",
    "STATUS_RECOVERED",
    "STATUS_RIGHT_CENSORED",
    "SignTestResult",
    "TRAINING_SEEDS",
    "Transition",
    "UpdateBatch",
    "WINDOW",
    "WilcoxonResult",
    "bootstrap_percentile_ci",
    "build_schedule",
    "build_update_batch",
    "call_update_atomically",
    "cohen_dz",
    "compute_recovery",
    "decide_family",
    "derive_seed",
    "exact_sign_test",
    "exact_wilcoxon_signed_rank",
    "final_window_return",
    "final_window_success_rate",
    "frozen_schedule",
    "holm_adjust",
    "impute_differences",
    "paired_differences",
    "paired_t_interval",
    "paired_t_test",
    "recovery_threshold_met",
    "schedule_fingerprint",
    "student_t_cdf",
    "student_t_ppf",
    "trailing_window_means",
    "validate_block_sequence",
    "validate_schedule",
]
